### PR TITLE
Generalize submit.sh

### PR DESCRIPTION
**Pull request by dberzano**
It is now possible to use it on any Linux node, not only on Slurm. Requisites:
  * Singularity v3+
  * /cvmfs

### CODE REVIEW

**Comment by dberzano** [comment]
Pending: it works on Linux, it has to be tested back on Slurm now

**Review by mconcas — APPROVED** [review]

**Comment by mconcas** [comment]
Thanks @dberzano

**Review by mconcas — COMMENTED** [review]
Well, apparently somewhere this is broken, probably some environment is not propagated to singularity/ some path is not accessible from within the container.
Investigating.
```bash
Working from /scratch_local/slurm_job.5704042/tmp.SBA2JHbFPi
SUBMIT variables already set
mktemp: failed to create directory via template '/scratch_local/slurm_job.5704042/tmp.XXXXXXXXXX': No such file or directory
Working from /dummy_home
```
I guess this is a revert.

**Comment by mconcas** [comment]
fixed in #5

**Pull request merged**
